#!/usr/bin/env python3

import sys

from lib.gridLoader import GridLoader


def main():
    if len(sys.argv) < 2:
        print("Usage: ./hashi GRID...")
        exit(1)

    for arg in sys.argv[1:]:
        grid = GridLoader(arg).load()
        print("Trying to solve : " + arg + "\n")
        grid.display()
        solution = grid.solve()
        print("")
        if solution == None:
            print("No solution found.")
        else:
            print("A result, here is :\n")
            solution.display()
            print("")


main()
