#!/usr/bin/env python3

import sys

from lib.gridLoader import GridLoader


def main():
    if len(sys.argv) < 2:
        print("Usage: ./hashi GRID...")
        exit(1)

    for arg in sys.argv[1:]:
        grid = GridLoader.load(arg)

        print("Trying to solve: " + arg + "...\n")
        grid.displayMatrix()
        print("")

        solution = grid.solve()
        if solution == False:
            print("No Island in the Grid.")
        elif solution == None:
            print("No solution found.")
        else:
            print("A great result, here is:\n")
            solution.display()
            print("")


main()
