#!/usr/bin/env python3

import sys

from lib.gridLoader import GridLoader


def main():
    if len(sys.argv) < 2:
        print("Usage: ./hashi GRID...")
        exit(1)

    for arg in sys.argv[1:]:
        grid = GridLoader(arg).load()
        solution = grid.solve()
        if solution == None:
            print(arg + ": no solution found")
        else:
            print(arg + ": a result, here is")
            solution.display()
            print("")


main()
